"""
Part 1, Task 2 — Seed data generator.

Reads data/customers.csv, data/products.csv, data/orders.csv and writes
sql/seed_data.sql as INSERT statements. Blank CSV cells become SQL NULL
(not '' or 0), so COUNT(rating) correctly returns 165.

"""
import csv

NUMBER_COLS = {"city_tier", "price", "quantity", "discount_pct", "rating", "returned"}


def to_sql(value, is_number):
    """Convert one CSV cell into a SQL value."""
    value = value.strip()
    if value == "":
        return "NULL"                               # blank cell → NULL
    if is_number:
        return value                                # 25 → 25
    return "'" + value.replace("'", "''") + "'"     # Aarav → 'Aarav'


def table_inserts(table):
    """Turn one CSV file into a list of INSERT statements."""
    lines = []
    with open(f"data/{table}.csv", newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames
        col_list = ", ".join(cols)
        for row in reader:
            values = ", ".join(to_sql(row[c], c in NUMBER_COLS) for c in cols)
            lines.append(f"INSERT INTO {table} ({col_list}) VALUES ({values});")
    return lines


all_lines = [
    "-- Part 1, Task 2 — Seed data (AUTO-GENERATED by sql/build_seed.py from data/*.csv)",
    "-- Run after schema.sql. Blank CSV cells are loaded as NULL.",
    "USE mamaearth;",
    "",
]

for t in ["customers", "products", "orders"]:     # parents first, because of foreign keys
    rows = table_inserts(t)
    print(t, len(rows))
    all_lines.append(f"-- {t}: {len(rows)} rows")
    all_lines.extend(rows)
    all_lines.append("")

with open("sql/seed_data.sql", "w", encoding="utf-8") as f:
    f.write("\n".join(all_lines))

print("seed_data.sql written")



